#!/bin/bash
# =============================================================================
# Demo & Deployment Pipeline Tool
# Built by Hoss — Autonomous DevRel + QA Agent
# =============================================================================
# Usage:
#   ./demo_pipeline.sh --app-name "AppName" \
#                       --source "https://github.com/user/repo" \
#                       --flows "click Login, enter creds, submit" \
#                       --codeberg-user "tylerdotai" \
#                       --codeberg-token "TOKEN" \
#                       --port 3000
# =============================================================================

set -e

# -------------------------------------------------------------------
# Parse Arguments
# -------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case $1 in
        --app-name) APP_NAME="$2"; shift 2 ;;
        --source) SOURCE="$2"; shift 2 ;;
        --flows) TARGET_FLOWS="$2"; shift 2 ;;
        --codeberg-user) CODEBERG_USER="$2"; shift 2 ;;
        --codeberg-token) CODEBERG_TOKEN="$2"; shift 2 ;;
        --port) TARGET_PORT="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# Validate required args
for var in APP_NAME SOURCE CODEBERG_USER CODEBERG_TOKEN; do
    if [ -z "${!var}" ]; then
        echo "ERROR: Missing required argument --${var,,}"
        exit 1
    fi
done

TARGET_PORT="${TARGET_PORT:-3000}"
TARGET_DIR="$HOME/Desktop/client_demos/${APP_NAME}"
ASSETS_DIR="${TARGET_DIR}/assets"
SCREENSHOTS_DIR="${ASSETS_DIR}/screenshots"

echo "========================================"
echo "  DEMO PIPELINE — ${APP_NAME}"
echo "========================================"
echo "  Source:     ${SOURCE}"
echo "  Target:     ${TARGET_DIR}"
echo "  Port:       ${TARGET_PORT}"
echo "  Flows:      ${TARGET_FLOWS}"
echo "========================================"

# =============================================================================
# PHASE 1: INGESTION & BUILD
# =============================================================================
echo ""
echo "[PHASE 1] Ingestion & Build"

# Create target directory
mkdir -p "${TARGET_DIR}"
rm -rf "${TARGET_DIR}"/*

# Clone or download source
if [[ "$SOURCE" == http* ]]; then
    echo "Cloning repository..."
    git clone --depth 1 "$SOURCE" "${TARGET_DIR}"
else
    echo "Copying from local path..."
    cp -r "$SOURCE"/. "${TARGET_DIR}/"
fi

cd "${TARGET_DIR}"
echo "Contents: $(ls -la)"

# Detect package manager and install
if [ -f "package.json" ]; then
    echo "Detected: npm package"
    npm install
    BUILD_CMD="npm start"
elif [ -f "requirements.txt" ]; then
    echo "Detected: Python package"
    pip install -r requirements.txt
    if [ -f "manage.py" ]; then
        BUILD_CMD="python manage.py runserver ${TARGET_PORT}"
    elif [ -f "app.py" ]; then
        BUILD_CMD="python app.py"
    else
        BUILD_CMD="python -m flask run --port ${TARGET_PORT}"
    fi
elif [ -f "Cargo.toml" ]; then
    echo "Detected: Rust/Cargo package"
    cargo build --release
    BUILD_CMD="./target/release/${APP_NAME}"
elif [ -f "go.mod" ]; then
    echo "Detected: Go package"
    go build -o "${APP_NAME}"
    BUILD_CMD="./${APP_NAME}"
else
    echo "Could not detect package manager — attempting generic build"
    BUILD_CMD=""
fi

# Start the app in background
echo "Starting application on port ${TARGET_PORT}..."
eval "$BUILD_CMD" &
APP_PID=$!
echo "App PID: $APP_PID"

# Wait for app to be ready
echo "Waiting for app to be ready..."
for i in {1..30}; do
    if curl -s "http://localhost:${TARGET_PORT}" > /dev/null 2>&1; then
        echo "App is up!"
        break
    fi
    sleep 2
done

# =============================================================================
# PHASE 2: ANALYSIS & DOCUMENTATION
# =============================================================================
echo ""
echo "[PHASE 2] Analysis & Documentation"

# Create assets directories
mkdir -p "${SCREENSHOTS_DIR}"

# Analyze codebase structure
echo "Analyzing codebase..."
CORE_FILES=$(find . -maxdepth 3 -type f \( -name "*.py" -o -name "*.js" -o -name "*.ts" -o -name "*.tsx" -o -name "*.jsx" -o -name "*.go" -o -name "*.rs" \) | head -20)
echo "Core files found:"
echo "$CORE_FILES"

# Detect entry points
if [ -f "package.json" ]; then
    ENTRY_POINT=$(node -e "console.log(JSON.parse(require('fs').readFileSync('package.json')).main || 'index.js')")
elif [ -f "app.py" ]; then
    ENTRY_POINT="app.py"
elif [ -f "main.py" ]; then
    ENTRY_POINT="main.py"
elif [ -f "main.go" ]; then
    ENTRY_POINT="main.go"
else
    ENTRY_POINT="(unknown)"
fi
echo "Entry point: $ENTRY_POINT"

# Generate README.md
cat > "${TARGET_DIR}/README.md" << 'README_EOF'
# {{APP_NAME}}

> Demo & Documentation generated by Hoss — Autonomous DevRel Agent

## 📌 Project Overview

{{APP_NAME}} is a modern application built with industry-standard tooling.

## ✨ Core Features

- Feature 1
- Feature 2
- Feature 3

## 🛠️ Local Installation

```bash
# Clone the repository
git clone <repo-url>
cd {{APP_NAME}}

# Install dependencies
npm install  # or pip install -r requirements.txt

# Run the application
npm start  # or python app.py
```

## 📖 Usage

1. Navigate to `http://localhost:{{PORT}}`
2. Complete the primary user flows
3. Explore settings and configurations

## 🎥 Demo & Assets

> Visual demo and UI screenshots captured during automated demo run.

**Screen Recording:** ./assets/demo.mp4

**Screenshots:** ./assets/screenshots/

## 📂 Project Structure

```
{{APP_NAME}}/
├── README.md
├── assets/
│   ├── demo.mp4
│   └── screenshots/
├── package.json  # or requirements.txt
└── src/          # core application code
```

---
*Documentation auto-generated by Hoss Demo Pipeline*
README_EOF

# Substitute variables
sed -i '' "s/{{APP_NAME}}/${APP_NAME}/g" "${TARGET_DIR}/README.md"
sed -i '' "s/{{PORT}}/${TARGET_PORT}/g" "${TARGET_DIR}/README.md"
sed -i '' "s|{{SOURCE}}|${SOURCE}|g" "${TARGET_DIR}/README.md"

echo "README.md generated!"

# =============================================================================
# PHASE 3: UI CAPTURE & DEMO
# =============================================================================
echo ""
echo "[PHASE 3] UI Capture & Demo"

# Bring app window to front (macOS)
osascript -e 'tell application "Safari" to activate' 2>/dev/null || \
osascript -e 'tell application "Chrome" to activate' 2>/dev/null || \
osascript -e 'tell application "System Events" to keystroke "r" using command down' 2>/dev/null || \
echo "Browser focus: manual intervention may be needed"

sleep 2

# Capture screenshots (4 views)
echo "Capturing screenshots..."
screencapture -x "${SCREENSHOTS_DIR}/screen_1.png" 2>/dev/null && echo "  ✓ screen_1.png"
sleep 1
screencapture -x "${SCREENSHOTS_DIR}/screen_2.png" 2>/dev/null && echo "  ✓ screen_2.png"
sleep 1
screencapture -x "${SCREENSHOTS_DIR}/screen_3.png" 2>/dev/null && echo "  ✓ screen_3.png"
sleep 1
screencapture -x "${SCREENSHOTS_DIR}/screen_4.png" 2>/dev/null && echo "  ✓ screen_4.png"

# Start screen recording
echo "Starting screen recording..."
screencapture -v "${ASSETS_DIR}/demo.mp4" &
RECORD_PID=$!
echo "Recording PID: $RECORD_PID"

# Wait a moment for recording to start
sleep 2

echo "DEMO_FLOWS: ${TARGET_FLOWS}"
echo "Performing demo — user will interact manually..."
echo "Press Enter when demo is complete..."
read -r _

# Stop recording
echo "Stopping recording..."
kill -INT $RECORD_PID 2>/dev/null || killall screencapture 2>/dev/null
sleep 1

# Verify assets
if [ -f "${ASSETS_DIR}/demo.mp4" ]; then
    MP4_SIZE=$(stat -f%z "${ASSETS_DIR}/demo.mp4" 2>/dev/null || stat -c%s "${ASSETS_DIR}/demo.mp4" 2>/dev/null)
    echo "✓ demo.mp4 exists (${MP4_SIZE} bytes)"
else
    echo "⚠️ demo.mp4 not found"
fi

# =============================================================================
# PHASE 4: CODEBERG DEPLOYMENT
# =============================================================================
echo ""
echo "[PHASE 4] Codeberg Deployment"

cd "${TARGET_DIR}"

# Git init
git init
git add .
git commit -m "Initial commit: Codebase, README, and Demo Assets"

# Create repo via Codeberg API
echo "Creating Codeberg repository..."
CREATE_RESP=$(curl -s -X POST "https://codeberg.org/api/v1/user/repos" \
    -H "accept: application/json" \
    -H "Authorization: token ${CODEBERG_TOKEN}" \
    -H "Content-Type: application/json" \
    -d "{\"name\":\"${APP_NAME}\",\"private\":false}")

echo "API Response: $CREATE_RESP"

REPO_URL="https://codeberg.org/${CODEBERG_USER}/${APP_NAME}.git"

# Add remote and push
git remote add origin "${REPO_URL}"
git push -u origin main 2>&1 || git push -u origin master 2>&1

echo "✓ Pushed to ${REPO_URL}"

# =============================================================================
# PHASE 5: REPORTING
# =============================================================================
echo ""
echo "[PHASE 5] Reporting"

# Kill dev server
kill $APP_PID 2>/dev/null || true
echo "Dev server stopped."

echo ""
echo "========================================"
echo "  ✅ PIPELINE COMPLETE"
echo "========================================"
echo "  📦 Codeberg: ${REPO_URL}"
echo "  📂 Local:    ${TARGET_DIR}"
echo "  🎥 Demo:     ${ASSETS_DIR}/demo.mp4"
echo "  📸 Screens:  ${SCREENSHOTS_DIR}/"
echo "========================================"
